# Icon
favicon: /favicon.ico
# SEO
keywords: Hexo, Gruntjs, Nodejs, Reactjs, Vuejs
# Header
page_background: https://i.loli.net/2018/11/05/5bdfeccbb2696.jpg
page_menu_button: dark
post_background: https://i.loli.net/2018/11/05/5bdfeccbb2696.jpg
post_menu_button: light
title_plancehold: 随笔
author:
  head: https://i.loli.net/2018/11/05/5bdfe65918658.jpg
  signature: 晚来天欲雪，能饮一杯无？
navication:
  - name: Github
    link: https://github.com/huangy10
  - name: Archives
    link: /archives
# content
content_width: 800
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: https://github.com/huangy10
  - name: Zhihu
    icon: zhihu
    link: https://www.zhihu.com/people/woody-huang
  - name: Email
    icon: email
    link: mailto:woodyhuang1@gmail.com

# Copyright
copyright:
  record: false
  hexo: true
  laughing: true

# 评论目前支持valine, laibili
# https://valine.js.org/
# Valine 诞生于2017年8月7日，是一款基于Leancloud的快速、简洁且高效的无后端评论系统
# https://leancloud.cn/ 你需要去这个网站注册账户，启用一个应用来获取appId和appKey。个人博客使用免费的就够用了
comments:
  # provider: valine
  # apiId: '<your-app-id>'
  # appKey: '<your-app-key>'

  provider: laibili
  uid: MTAyMC80MDkyMC8xNzQ0NQ==
  
