# Icon
favicon: /favicon.ico
# SEO
keywords: Hexo, Gruntjs, Nodejs, Reactjs, Vuejs
# Header
page_background: https://i.loli.net/2018/11/05/5bdfeccbb2696.jpg
page_menu_button: dark
post_background: https://i.loli.net/2018/11/05/5bdfeccbb2696.jpg
post_menu_button: light
title_plancehold: 随笔
author:
  head: http://callfiles.ueibo.com/hexo-theme-laughing/thumb.jpg
  signature: Only when you plant the flowers can you really smell their fragrance.
navication:
  - name: Github
    link: https://github.com
  - name: V2EX
    link: https://www.v2ex.com/
# content
content_width: 800
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: https://github.com/huangy10
  - name: Zhihu
    icon: zhihu
    link: https://www.zhihu.com/people/woody-huang
  - name: Email
    icon: email
    link: mailto:woodyhuang1@gmail.com

# Copyright
copyright:
  record: false
  hexo: true
  laughing: true